# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adSfcUseDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_adSfcUseDialog(object):
    def setupUi(self, adSfcUseDialog):
        adSfcUseDialog.setObjectName("adSfcUseDialog")
        adSfcUseDialog.resize(315, 412)
        self.verticalLayout = QtWidgets.QVBoxLayout(adSfcUseDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rwyUse_box = QtWidgets.QGroupBox(adSfcUseDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rwyUse_box.sizePolicy().hasHeightForWidth())
        self.rwyUse_box.setSizePolicy(sizePolicy)
        self.rwyUse_box.setObjectName("rwyUse_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rwyUse_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rwyUse_tableView = QtWidgets.QTableView(self.rwyUse_box)
        self.rwyUse_tableView.setObjectName("rwyUse_tableView")
        self.rwyUse_tableView.horizontalHeader().setStretchLastSection(True)
        self.rwyUse_tableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.rwyUse_tableView)
        self.avoidOppositeRunways_tickBox = QtWidgets.QCheckBox(self.rwyUse_box)
        self.avoidOppositeRunways_tickBox.setChecked(True)
        self.avoidOppositeRunways_tickBox.setObjectName("avoidOppositeRunways_tickBox")
        self.verticalLayout_2.addWidget(self.avoidOppositeRunways_tickBox)
        self.verticalLayout.addWidget(self.rwyUse_box)
        self.helipadUse_box = QtWidgets.QGroupBox(adSfcUseDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helipadUse_box.sizePolicy().hasHeightForWidth())
        self.helipadUse_box.setSizePolicy(sizePolicy)
        self.helipadUse_box.setObjectName("helipadUse_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.helipadUse_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.helipadUse_tableView = QtWidgets.QTableView(self.helipadUse_box)
        self.helipadUse_tableView.setObjectName("helipadUse_tableView")
        self.helipadUse_tableView.horizontalHeader().setVisible(False)
        self.helipadUse_tableView.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.helipadUse_tableView)
        self.verticalLayout.addWidget(self.helipadUse_box)
        self.buttonBox = QtWidgets.QDialogButtonBox(adSfcUseDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(adSfcUseDialog)
        QtCore.QMetaObject.connectSlotsByName(adSfcUseDialog)
        adSfcUseDialog.setTabOrder(self.rwyUse_tableView, self.buttonBox)

    def retranslateUi(self, adSfcUseDialog):
        _translate = QtCore.QCoreApplication.translate
        adSfcUseDialog.setWindowTitle(_translate("adSfcUseDialog", "TKOF/LDG surfaces use"))
        self.rwyUse_box.setTitle(_translate("adSfcUseDialog", "Runways"))
        self.avoidOppositeRunways_tickBox.setText(_translate("adSfcUseDialog", "Deselect opposite runways"))
        self.helipadUse_box.setTitle(_translate("adSfcUseDialog", "Helipads"))
