# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'airportSearchWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_airportSearchWidget(object):
    def setupUi(self, airportSearchWidget):
        airportSearchWidget.setObjectName("airportSearchWidget")
        airportSearchWidget.resize(567, 645)
        self.verticalLayout = QtWidgets.QVBoxLayout(airportSearchWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(airportSearchWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.filter_edit = QtWidgets.QLineEdit(airportSearchWidget)
        self.filter_edit.setClearButtonEnabled(True)
        self.filter_edit.setObjectName("filter_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.filter_edit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(airportSearchWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.codeFilter_radioButton = QtWidgets.QRadioButton(airportSearchWidget)
        self.codeFilter_radioButton.setObjectName("codeFilter_radioButton")
        self.horizontalLayout_2.addWidget(self.codeFilter_radioButton)
        self.nameFilter_radioButton = QtWidgets.QRadioButton(airportSearchWidget)
        self.nameFilter_radioButton.setChecked(True)
        self.nameFilter_radioButton.setObjectName("nameFilter_radioButton")
        self.horizontalLayout_2.addWidget(self.nameFilter_radioButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.search_button = QtWidgets.QToolButton(airportSearchWidget)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table_view = QtWidgets.QTableView(airportSearchWidget)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.table_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.table_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.table_view.setShowGrid(False)
        self.table_view.setSortingEnabled(True)
        self.table_view.setObjectName("table_view")
        self.table_view.horizontalHeader().setStretchLastSection(True)
        self.table_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_view)
        self.map_view = WorldMapView(airportSearchWidget)
        self.map_view.setDragMode(QtWidgets.QGraphicsView.ScrollHandDrag)
        self.map_view.setTransformationAnchor(QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.map_view.setObjectName("map_view")
        self.verticalLayout.addWidget(self.map_view)
        self.label.setBuddy(self.filter_edit)
        self.label_2.setBuddy(self.codeFilter_radioButton)

        self.retranslateUi(airportSearchWidget)
        self.codeFilter_radioButton.toggled['bool'].connect(self.filter_edit.setFocus) # type: ignore
        self.filter_edit.returnPressed.connect(self.search_button.animateClick) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(airportSearchWidget)
        airportSearchWidget.setTabOrder(self.filter_edit, self.codeFilter_radioButton)
        airportSearchWidget.setTabOrder(self.codeFilter_radioButton, self.nameFilter_radioButton)

    def retranslateUi(self, airportSearchWidget):
        _translate = QtCore.QCoreApplication.translate
        airportSearchWidget.setWindowTitle(_translate("airportSearchWidget", "Airport search"))
        self.label.setText(_translate("airportSearchWidget", "Filter:"))
        self.filter_edit.setToolTip(_translate("airportSearchWidget", "Case insensitive regexp search"))
        self.label_2.setText(_translate("airportSearchWidget", "Search in:"))
        self.codeFilter_radioButton.setText(_translate("airportSearchWidget", "codes"))
        self.nameFilter_radioButton.setText(_translate("airportSearchWidget", "names"))
        self.search_button.setText(_translate("airportSearchWidget", "Search"))
from gui.graphics.worldMap import WorldMapView
