# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarmClocksPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_alarmClocksPanel(object):
    def setupUi(self, alarmClocksPanel):
        alarmClocksPanel.setObjectName("alarmClocksPanel")
        alarmClocksPanel.resize(463, 228)
        self.verticalLayout = QtWidgets.QVBoxLayout(alarmClocksPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.timers_view = QtWidgets.QTableView(alarmClocksPanel)
        self.timers_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.timers_view.setObjectName("timers_view")
        self.timers_view.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.timers_view)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(alarmClocksPanel)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.newTimerDuration_edit = QtWidgets.QSpinBox(alarmClocksPanel)
        self.newTimerDuration_edit.setMinimum(1)
        self.newTimerDuration_edit.setMaximum(999)
        self.newTimerDuration_edit.setObjectName("newTimerDuration_edit")
        self.horizontalLayout_2.addWidget(self.newTimerDuration_edit)
        self.newTimerStart_button = QtWidgets.QToolButton(alarmClocksPanel)
        self.newTimerStart_button.setObjectName("newTimerStart_button")
        self.horizontalLayout_2.addWidget(self.newTimerStart_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.deleteSelectedTimer_button = QtWidgets.QToolButton(alarmClocksPanel)
        self.deleteSelectedTimer_button.setObjectName("deleteSelectedTimer_button")
        self.horizontalLayout_2.addWidget(self.deleteSelectedTimer_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.close_button = QtWidgets.QPushButton(alarmClocksPanel)
        self.close_button.setObjectName("close_button")
        self.verticalLayout.addWidget(self.close_button)
        self.label.setBuddy(self.newTimerDuration_edit)

        self.retranslateUi(alarmClocksPanel)
        self.close_button.clicked.connect(alarmClocksPanel.hide) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(alarmClocksPanel)
        alarmClocksPanel.setTabOrder(self.timers_view, self.newTimerDuration_edit)
        alarmClocksPanel.setTabOrder(self.newTimerDuration_edit, self.newTimerStart_button)
        alarmClocksPanel.setTabOrder(self.newTimerStart_button, self.deleteSelectedTimer_button)
        alarmClocksPanel.setTabOrder(self.deleteSelectedTimer_button, self.close_button)

    def retranslateUi(self, alarmClocksPanel):
        _translate = QtCore.QCoreApplication.translate
        alarmClocksPanel.setWindowTitle(_translate("alarmClocksPanel", "Alarm clocks"))
        self.label.setText(_translate("alarmClocksPanel", "New timer:"))
        self.newTimerDuration_edit.setSuffix(_translate("alarmClocksPanel", " min"))
        self.newTimerStart_button.setText(_translate("alarmClocksPanel", "Start"))
        self.deleteSelectedTimer_button.setText(_translate("alarmClocksPanel", "Delete selected"))
        self.close_button.setText(_translate("alarmClocksPanel", "Close"))
