# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atcListPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atcListPanel(object):
    def setupUi(self, atcListPanel):
        atcListPanel.setObjectName("atcListPanel")
        atcListPanel.resize(338, 382)
        self.verticalLayout = QtWidgets.QVBoxLayout(atcListPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ATC_view = AtcTableView(atcListPanel)
        self.ATC_view.setAcceptDrops(True)
        self.ATC_view.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.ATC_view.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.ATC_view.setShowGrid(False)
        self.ATC_view.setObjectName("ATC_view")
        self.ATC_view.horizontalHeader().setVisible(False)
        self.ATC_view.verticalHeader().setVisible(False)
        self.ATC_view.verticalHeader().setDefaultSectionSize(35)
        self.verticalLayout.addWidget(self.ATC_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.call_button = QtWidgets.QToolButton(atcListPanel)
        self.call_button.setObjectName("call_button")
        self.horizontalLayout.addWidget(self.call_button)
        self.phoneSquelch_widget = QtWidgets.QWidget(atcListPanel)
        self.phoneSquelch_widget.setObjectName("phoneSquelch_widget")
        self.formLayout = QtWidgets.QFormLayout(self.phoneSquelch_widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.phoneSquelch_widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.phoneSquelch_edit = QtWidgets.QSpinBox(self.phoneSquelch_widget)
        self.phoneSquelch_edit.setMinimum(1)
        self.phoneSquelch_edit.setMaximum(20)
        self.phoneSquelch_edit.setObjectName("phoneSquelch_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.phoneSquelch_edit)
        self.horizontalLayout.addWidget(self.phoneSquelch_widget)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.whoHas_button = QtWidgets.QToolButton(atcListPanel)
        self.whoHas_button.setObjectName("whoHas_button")
        self.horizontalLayout.addWidget(self.whoHas_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.phoneSquelch_edit)

        self.retranslateUi(atcListPanel)
        QtCore.QMetaObject.connectSlotsByName(atcListPanel)
        atcListPanel.setTabOrder(self.ATC_view, self.call_button)
        atcListPanel.setTabOrder(self.call_button, self.phoneSquelch_edit)
        atcListPanel.setTabOrder(self.phoneSquelch_edit, self.whoHas_button)

    def retranslateUi(self, atcListPanel):
        _translate = QtCore.QCoreApplication.translate
        self.call_button.setToolTip(_translate("atcListPanel", "Place a phone call"))
        self.call_button.setText(_translate("atcListPanel", "Call..."))
        self.label.setText(_translate("atcListPanel", "Squelch:"))
        self.phoneSquelch_edit.setToolTip(_translate("atcListPanel", "Adjust microphone sensitivity in phone calls"))
        self.whoHas_button.setToolTip(_translate("atcListPanel", "Send out a who-has query"))
        self.whoHas_button.setText(_translate("atcListPanel", "Who has?"))
from gui.widgets.atcTableView import AtcTableView
