# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atcTextChatPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_atcTextChatPanel(object):
    def setupUi(self, atcTextChatPanel):
        atcTextChatPanel.setObjectName("atcTextChatPanel")
        atcTextChatPanel.resize(470, 379)
        self.verticalLayout = QtWidgets.QVBoxLayout(atcTextChatPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.publicChannel_radioButton = QtWidgets.QRadioButton(atcTextChatPanel)
        self.publicChannel_radioButton.setObjectName("publicChannel_radioButton")
        self.horizontalLayout_2.addWidget(self.publicChannel_radioButton)
        self.privateChannel_radioButton = QtWidgets.QRadioButton(atcTextChatPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.privateChannel_radioButton.sizePolicy().hasHeightForWidth())
        self.privateChannel_radioButton.setSizePolicy(sizePolicy)
        self.privateChannel_radioButton.setObjectName("privateChannel_radioButton")
        self.horizontalLayout_2.addWidget(self.privateChannel_radioButton)
        self.privateChannel_edit = QtWidgets.QComboBox(atcTextChatPanel)
        self.privateChannel_edit.setEnabled(False)
        self.privateChannel_edit.setEditable(True)
        self.privateChannel_edit.setObjectName("privateChannel_edit")
        self.horizontalLayout_2.addWidget(self.privateChannel_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.chatHistory_view = QtWidgets.QTableView(atcTextChatPanel)
        self.chatHistory_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.chatHistory_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.chatHistory_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.chatHistory_view.setShowGrid(False)
        self.chatHistory_view.setObjectName("chatHistory_view")
        self.chatHistory_view.horizontalHeader().setVisible(False)
        self.chatHistory_view.horizontalHeader().setStretchLastSection(True)
        self.chatHistory_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.chatHistory_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.msgLine_edit = QtWidgets.QLineEdit(atcTextChatPanel)
        self.msgLine_edit.setClearButtonEnabled(True)
        self.msgLine_edit.setObjectName("msgLine_edit")
        self.horizontalLayout.addWidget(self.msgLine_edit)
        self.send_button = QtWidgets.QToolButton(atcTextChatPanel)
        self.send_button.setEnabled(True)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(atcTextChatPanel)
        self.privateChannel_radioButton.toggled['bool'].connect(self.privateChannel_edit.setEnabled) # type: ignore
        self.privateChannel_radioButton.toggled['bool'].connect(self.privateChannel_edit.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(atcTextChatPanel)
        atcTextChatPanel.setTabOrder(self.msgLine_edit, self.send_button)
        atcTextChatPanel.setTabOrder(self.send_button, self.publicChannel_radioButton)
        atcTextChatPanel.setTabOrder(self.publicChannel_radioButton, self.privateChannel_radioButton)
        atcTextChatPanel.setTabOrder(self.privateChannel_radioButton, self.privateChannel_edit)
        atcTextChatPanel.setTabOrder(self.privateChannel_edit, self.chatHistory_view)

    def retranslateUi(self, atcTextChatPanel):
        _translate = QtCore.QCoreApplication.translate
        atcTextChatPanel.setWindowTitle(_translate("atcTextChatPanel", "ATC text messaging"))
        self.publicChannel_radioButton.setText(_translate("atcTextChatPanel", "Public channel"))
        self.privateChannel_radioButton.setText(_translate("atcTextChatPanel", "Private:"))
        self.send_button.setText(_translate("atcTextChatPanel", "Send"))
