# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fplPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fplPanel(object):
    def setupUi(self, fplPanel):
        fplPanel.setObjectName("fplPanel")
        fplPanel.resize(445, 345)
        self.verticalLayout = QtWidgets.QVBoxLayout(fplPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(fplPanel)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.filterStatus_button = QtWidgets.QToolButton(fplPanel)
        self.filterStatus_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.filterStatus_button.setObjectName("filterStatus_button")
        self.horizontalLayout.addWidget(self.filterStatus_button)
        self.filterCallsign_edit = QtWidgets.QLineEdit(fplPanel)
        self.filterCallsign_edit.setClearButtonEnabled(True)
        self.filterCallsign_edit.setObjectName("filterCallsign_edit")
        self.horizontalLayout.addWidget(self.filterCallsign_edit)
        self.filterArrDep_button = QtWidgets.QToolButton(fplPanel)
        self.filterArrDep_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.filterArrDep_button.setObjectName("filterArrDep_button")
        self.horizontalLayout.addWidget(self.filterArrDep_button)
        self.filterDate_button = QtWidgets.QToolButton(fplPanel)
        self.filterDate_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.filterDate_button.setObjectName("filterDate_button")
        self.horizontalLayout.addWidget(self.filterDate_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.list_view = FlightPlanTableView(fplPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_view.sizePolicy().hasHeightForWidth())
        self.list_view.setSizePolicy(sizePolicy)
        self.list_view.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.list_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.list_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.list_view.setObjectName("list_view")
        self.list_view.horizontalHeader().setStretchLastSection(True)
        self.list_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.list_view)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.localActions_menuButton = QtWidgets.QToolButton(fplPanel)
        self.localActions_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.localActions_menuButton.setObjectName("localActions_menuButton")
        self.horizontalLayout_3.addWidget(self.localActions_menuButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.onlineActions_menuButton = QtWidgets.QToolButton(fplPanel)
        self.onlineActions_menuButton.setEnabled(False)
        self.onlineActions_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.onlineActions_menuButton.setObjectName("onlineActions_menuButton")
        self.horizontalLayout_3.addWidget(self.onlineActions_menuButton)
        self.checkNow_button = QtWidgets.QToolButton(fplPanel)
        self.checkNow_button.setEnabled(False)
        self.checkNow_button.setObjectName("checkNow_button")
        self.horizontalLayout_3.addWidget(self.checkNow_button)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label.setBuddy(self.filterStatus_button)

        self.retranslateUi(fplPanel)
        QtCore.QMetaObject.connectSlotsByName(fplPanel)
        fplPanel.setTabOrder(self.list_view, self.filterStatus_button)
        fplPanel.setTabOrder(self.filterStatus_button, self.filterCallsign_edit)
        fplPanel.setTabOrder(self.filterCallsign_edit, self.filterArrDep_button)
        fplPanel.setTabOrder(self.filterArrDep_button, self.filterDate_button)
        fplPanel.setTabOrder(self.filterDate_button, self.localActions_menuButton)
        fplPanel.setTabOrder(self.localActions_menuButton, self.onlineActions_menuButton)
        fplPanel.setTabOrder(self.onlineActions_menuButton, self.checkNow_button)

    def retranslateUi(self, fplPanel):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("fplPanel", "Filter:"))
        self.filterStatus_button.setToolTip(_translate("fplPanel", "Filter by online status"))
        self.filterStatus_button.setText(_translate("fplPanel", "Status"))
        self.filterCallsign_edit.setToolTip(_translate("fplPanel", "Filter by callsign"))
        self.filterCallsign_edit.setPlaceholderText(_translate("fplPanel", "Callsign"))
        self.filterArrDep_button.setToolTip(_translate("fplPanel", "Filter by ARR/DEP/alternate airfield"))
        self.filterArrDep_button.setText(_translate("fplPanel", "AD"))
        self.filterDate_button.setToolTip(_translate("fplPanel", "Filter by scheduled date"))
        self.filterDate_button.setText(_translate("fplPanel", "Date"))
        self.localActions_menuButton.setText(_translate("fplPanel", "Local"))
        self.onlineActions_menuButton.setText(_translate("fplPanel", "Online"))
        self.checkNow_button.setToolTip(_translate("fplPanel", "Check for online updates"))
        self.checkNow_button.setText(_translate("fplPanel", "Check now"))
from gui.widgets.fplTableView import FlightPlanTableView
