# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'helipadParamsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_helipadParamsWidget(object):
    def setupUi(self, helipadParamsWidget):
        helipadParamsWidget.setObjectName("helipadParamsWidget")
        helipadParamsWidget.setEnabled(True)
        helipadParamsWidget.resize(278, 202)
        self.verticalLayout = QtWidgets.QVBoxLayout(helipadParamsWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.helipadName_info = QtWidgets.QLabel(helipadParamsWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        self.helipadName_info.setFont(font)
        self.helipadName_info.setFrameShape(QtWidgets.QFrame.Box)
        self.helipadName_info.setAlignment(QtCore.Qt.AlignCenter)
        self.helipadName_info.setObjectName("helipadName_info")
        self.verticalLayout.addWidget(self.helipadName_info)
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.preferredDep_groupBox = QtWidgets.QGroupBox(helipadParamsWidget)
        self.preferredDep_groupBox.setEnabled(True)
        self.preferredDep_groupBox.setChecked(False)
        self.preferredDep_groupBox.setObjectName("preferredDep_groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.preferredDep_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.preferredDep_groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.preferredDepCourse_edit = QtWidgets.QSpinBox(self.preferredDep_groupBox)
        self.preferredDepCourse_edit.setWrapping(True)
        self.preferredDepCourse_edit.setMaximum(359)
        self.preferredDepCourse_edit.setObjectName("preferredDepCourse_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.preferredDepCourse_edit)
        self.verticalLayout.addWidget(self.preferredDep_groupBox)
        self.label.setBuddy(self.preferredDepCourse_edit)

        self.retranslateUi(helipadParamsWidget)
        QtCore.QMetaObject.connectSlotsByName(helipadParamsWidget)

    def retranslateUi(self, helipadParamsWidget):
        _translate = QtCore.QCoreApplication.translate
        self.helipadName_info.setText(_translate("helipadParamsWidget", "###"))
        self.preferredDep_groupBox.setTitle(_translate("helipadParamsWidget", "Preferred/default departure"))
        self.label.setText(_translate("helipadParamsWidget", "Heading:"))
        self.preferredDepCourse_edit.setSpecialValueText(_translate("helipadParamsWidget", "360°"))
        self.preferredDepCourse_edit.setSuffix(_translate("helipadParamsWidget", "°"))
