# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'looseStripPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_looseStripPanel(object):
    def setupUi(self, looseStripPanel):
        looseStripPanel.setObjectName("looseStripPanel")
        looseStripPanel.resize(578, 363)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(looseStripPanel.sizePolicy().hasHeightForWidth())
        looseStripPanel.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(looseStripPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stripView = QtWidgets.QGraphicsView(looseStripPanel)
        self.stripView.setInteractive(True)
        self.stripView.setObjectName("stripView")
        self.verticalLayout.addWidget(self.stripView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.background_menuButton = QtWidgets.QToolButton(looseStripPanel)
        self.background_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.background_menuButton.setObjectName("background_menuButton")
        self.horizontalLayout_3.addWidget(self.background_menuButton)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.compactStrips_tickBox = QtWidgets.QCheckBox(looseStripPanel)
        self.compactStrips_tickBox.setObjectName("compactStrips_tickBox")
        self.horizontalLayout_3.addWidget(self.compactStrips_tickBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.strip_menuButton = StripMenuButton(looseStripPanel)
        self.strip_menuButton.setObjectName("strip_menuButton")
        self.horizontalLayout_3.addWidget(self.strip_menuButton)
        self.frame = QtWidgets.QFrame(looseStripPanel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shelf_button = ShelfButtonWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy)
        self.shelf_button.setMinimumSize(QtCore.QSize(50, 0))
        self.shelf_button.setObjectName("shelf_button")
        self.horizontalLayout.addWidget(self.shelf_button)
        self.horizontalLayout_3.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(looseStripPanel)
        QtCore.QMetaObject.connectSlotsByName(looseStripPanel)

    def retranslateUi(self, looseStripPanel):
        _translate = QtCore.QCoreApplication.translate
        looseStripPanel.setWindowTitle(_translate("looseStripPanel", "Loose strip bay"))
        self.background_menuButton.setText(_translate("looseStripPanel", "Bg"))
        self.compactStrips_tickBox.setText(_translate("looseStripPanel", "Compact strips"))
        self.strip_menuButton.setText(_translate("looseStripPanel", "..."))
from gui.widgets.stripView import ShelfButtonWidget, StripMenuButton
