# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notepadPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notepadPanel(object):
    def setupUi(self, notepadPanel):
        notepadPanel.setObjectName("notepadPanel")
        notepadPanel.resize(383, 531)
        self.verticalLayout = QtWidgets.QVBoxLayout(notepadPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(notepadPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.generalNotes_textEdit = QtWidgets.QPlainTextEdit(notepadPanel)
        self.generalNotes_textEdit.setObjectName("generalNotes_textEdit")
        self.verticalLayout.addWidget(self.generalNotes_textEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(notepadPanel)
        font = QtGui.QFont()
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.localNotes_textEdit = QtWidgets.QPlainTextEdit(notepadPanel)
        self.localNotes_textEdit.setObjectName("localNotes_textEdit")
        self.verticalLayout.addWidget(self.localNotes_textEdit)
        self.label_2.setBuddy(self.generalNotes_textEdit)
        self.label.setBuddy(self.localNotes_textEdit)

        self.retranslateUi(notepadPanel)
        QtCore.QMetaObject.connectSlotsByName(notepadPanel)

    def retranslateUi(self, notepadPanel):
        _translate = QtCore.QCoreApplication.translate
        notepadPanel.setWindowTitle(_translate("notepadPanel", "Form"))
        self.label_2.setText(_translate("notepadPanel", "General notes"))
        self.generalNotes_textEdit.setToolTip(_translate("notepadPanel", "Notes saved across all sessions"))
        self.label.setText(_translate("notepadPanel", "Local notes"))
        self.localNotes_textEdit.setToolTip(_translate("notepadPanel", "Notes saved for this location only"))
