# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'notifierPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notifierPanel(object):
    def setupUi(self, notifierPanel):
        notifierPanel.setObjectName("notifierPanel")
        notifierPanel.resize(323, 187)
        self.verticalLayout = QtWidgets.QVBoxLayout(notifierPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notification_table = QtWidgets.QTableView(notifierPanel)
        self.notification_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.notification_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.notification_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.notification_table.setShowGrid(False)
        self.notification_table.setWordWrap(False)
        self.notification_table.setObjectName("notification_table")
        self.notification_table.horizontalHeader().setVisible(False)
        self.notification_table.horizontalHeader().setStretchLastSection(True)
        self.notification_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.notification_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cleanUp_button = QtWidgets.QToolButton(notifierPanel)
        self.cleanUp_button.setObjectName("cleanUp_button")
        self.horizontalLayout.addWidget(self.cleanUp_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(notifierPanel)
        QtCore.QMetaObject.connectSlotsByName(notifierPanel)

    def retranslateUi(self, notifierPanel):
        _translate = QtCore.QCoreApplication.translate
        self.cleanUp_button.setText(_translate("notifierPanel", "Clear"))
