# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radioPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_radioPanel(object):
    def setupUi(self, radioPanel):
        radioPanel.setObjectName("radioPanel")
        radioPanel.resize(328, 315)
        self.verticalLayout = QtWidgets.QVBoxLayout(radioPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pubFreq_tickBox = QtWidgets.QCheckBox(radioPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pubFreq_tickBox.sizePolicy().hasHeightForWidth())
        self.pubFreq_tickBox.setSizePolicy(sizePolicy)
        self.pubFreq_tickBox.setObjectName("pubFreq_tickBox")
        self.horizontalLayout_3.addWidget(self.pubFreq_tickBox)
        self.pubFreq_edit = FrequencyPickCombo(radioPanel)
        self.pubFreq_edit.setEnabled(False)
        self.pubFreq_edit.setObjectName("pubFreq_edit")
        self.horizontalLayout_3.addWidget(self.pubFreq_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(radioPanel)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.radios_table = QtWidgets.QTableWidget(radioPanel)
        self.radios_table.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.radios_table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.radios_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.radios_table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.radios_table.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.radios_table.setColumnCount(1)
        self.radios_table.setObjectName("radios_table")
        self.radios_table.setRowCount(0)
        self.radios_table.horizontalHeader().setVisible(False)
        self.radios_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.radios_table)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addBox_button = QtWidgets.QToolButton(radioPanel)
        self.addBox_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.addBox_button.setObjectName("addBox_button")
        self.horizontalLayout.addWidget(self.addBox_button)
        self.atis_button = QtWidgets.QToolButton(radioPanel)
        self.atis_button.setEnabled(True)
        self.atis_button.setObjectName("atis_button")
        self.horizontalLayout.addWidget(self.atis_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.muteAllRadios_tickBox = QtWidgets.QToolButton(radioPanel)
        self.muteAllRadios_tickBox.setCheckable(True)
        self.muteAllRadios_tickBox.setObjectName("muteAllRadios_tickBox")
        self.horizontalLayout.addWidget(self.muteAllRadios_tickBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(radioPanel)
        self.pubFreq_tickBox.toggled['bool'].connect(self.pubFreq_edit.setEnabled) # type: ignore
        self.pubFreq_tickBox.toggled['bool'].connect(self.pubFreq_edit.setFocus) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(radioPanel)
        radioPanel.setTabOrder(self.radios_table, self.pubFreq_tickBox)
        radioPanel.setTabOrder(self.pubFreq_tickBox, self.pubFreq_edit)
        radioPanel.setTabOrder(self.pubFreq_edit, self.addBox_button)
        radioPanel.setTabOrder(self.addBox_button, self.atis_button)
        radioPanel.setTabOrder(self.atis_button, self.muteAllRadios_tickBox)

    def retranslateUi(self, radioPanel):
        _translate = QtCore.QCoreApplication.translate
        self.pubFreq_tickBox.setToolTip(_translate("radioPanel", "Publicise a frequency for your position"))
        self.pubFreq_tickBox.setText(_translate("radioPanel", "###"))
        self.addBox_button.setText(_translate("radioPanel", "Add radio"))
        self.atis_button.setText(_translate("radioPanel", "ATIS..."))
        self.muteAllRadios_tickBox.setToolTip(_translate("radioPanel", "Silence all radios"))
        self.muteAllRadios_tickBox.setText(_translate("radioPanel", "Silence"))
from gui.widgets.basicWidgets import FrequencyPickCombo
