# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recordTimelineDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_recordTimelineDialog(object):
    def setupUi(self, recordTimelineDialog):
        recordTimelineDialog.setObjectName("recordTimelineDialog")
        recordTimelineDialog.resize(384, 256)
        self.verticalLayout = QtWidgets.QVBoxLayout(recordTimelineDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(recordTimelineDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.recordTraffic_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.recordTraffic_tickBox.setObjectName("recordTraffic_tickBox")
        self.verticalLayout_3.addWidget(self.recordTraffic_tickBox)
        self.recordComms_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.recordComms_tickBox.setObjectName("recordComms_tickBox")
        self.verticalLayout_3.addWidget(self.recordComms_tickBox)
        self.recordWeather_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.recordWeather_tickBox.setObjectName("recordWeather_tickBox")
        self.verticalLayout_3.addWidget(self.recordWeather_tickBox)
        self.recordOther_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.recordOther_tickBox.setObjectName("recordOther_tickBox")
        self.verticalLayout_3.addWidget(self.recordOther_tickBox)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(recordTimelineDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dataFile_edit = QtWidgets.QLineEdit(recordTimelineDialog)
        self.dataFile_edit.setClearButtonEnabled(True)
        self.dataFile_edit.setObjectName("dataFile_edit")
        self.horizontalLayout.addWidget(self.dataFile_edit)
        self.browse_button = QtWidgets.QToolButton(recordTimelineDialog)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(recordTimelineDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label.setBuddy(self.dataFile_edit)

        self.retranslateUi(recordTimelineDialog)
        self.buttonBox.rejected.connect(recordTimelineDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(recordTimelineDialog)
        recordTimelineDialog.setTabOrder(self.recordTraffic_tickBox, self.recordComms_tickBox)
        recordTimelineDialog.setTabOrder(self.recordComms_tickBox, self.recordWeather_tickBox)
        recordTimelineDialog.setTabOrder(self.recordWeather_tickBox, self.recordOther_tickBox)
        recordTimelineDialog.setTabOrder(self.recordOther_tickBox, self.dataFile_edit)
        recordTimelineDialog.setTabOrder(self.dataFile_edit, self.browse_button)

    def retranslateUi(self, recordTimelineDialog):
        _translate = QtCore.QCoreApplication.translate
        recordTimelineDialog.setWindowTitle(_translate("recordTimelineDialog", "Record session timeline"))
        self.groupBox_2.setTitle(_translate("recordTimelineDialog", "Recorded data"))
        self.recordTraffic_tickBox.setToolTip(_translate("recordTimelineDialog", "Based on radar blips according to settings, even if not using radar in session"))
        self.recordTraffic_tickBox.setText(_translate("recordTimelineDialog", "ACFT traffic"))
        self.recordComms_tickBox.setToolTip(_translate("recordTimelineDialog", "Text radio and ATIS, RDF signals, CPDLC, ATC messaging and phone lines..."))
        self.recordComms_tickBox.setText(_translate("recordTimelineDialog", "Communications"))
        self.recordWeather_tickBox.setToolTip(_translate("recordTimelineDialog", "Based on monitored weather stations"))
        self.recordWeather_tickBox.setText(_translate("recordTimelineDialog", "Weather updates"))
        self.recordOther_tickBox.setToolTip(_translate("recordTimelineDialog", "E.g. strip handovers"))
        self.recordOther_tickBox.setText(_translate("recordTimelineDialog", "Other"))
        self.label.setText(_translate("recordTimelineDialog", "Output file:"))
        self.dataFile_edit.setToolTip(_translate("recordTimelineDialog", "If file exists, data will be appended"))
        self.browse_button.setToolTip(_translate("recordTimelineDialog", "Browse"))
        self.browse_button.setText(_translate("recordTimelineDialog", "..."))
