# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'routeEditWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_routeEditWidget(object):
    def setupUi(self, routeEditWidget):
        routeEditWidget.setObjectName("routeEditWidget")
        routeEditWidget.resize(309, 78)
        self.horizontalLayout = QtWidgets.QHBoxLayout(routeEditWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.route_edit = QtWidgets.QPlainTextEdit(routeEditWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.route_edit.sizePolicy().hasHeightForWidth())
        self.route_edit.setSizePolicy(sizePolicy)
        self.route_edit.setTabChangesFocus(True)
        self.route_edit.setObjectName("route_edit")
        self.horizontalLayout.addWidget(self.route_edit)
        self.view_button = QtWidgets.QToolButton(routeEditWidget)
        self.view_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.view_button.setAutoRaise(True)
        self.view_button.setObjectName("view_button")
        self.horizontalLayout.addWidget(self.view_button)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.suggest_button = QtWidgets.QToolButton(routeEditWidget)
        self.suggest_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.suggest_button.setAutoRaise(True)
        self.suggest_button.setObjectName("suggest_button")
        self.gridLayout.addWidget(self.suggest_button, 0, 0, 1, 1)
        self.saveAsPreset_button = QtWidgets.QToolButton(routeEditWidget)
        self.saveAsPreset_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveAsPreset_button.setAutoRaise(True)
        self.saveAsPreset_button.setObjectName("saveAsPreset_button")
        self.gridLayout.addWidget(self.saveAsPreset_button, 1, 1, 1, 1)
        self.clear_button = QtWidgets.QToolButton(routeEditWidget)
        self.clear_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.clear_button.setAutoRaise(True)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout.addWidget(self.clear_button, 1, 0, 1, 1)
        self.recallPreset_button = QtWidgets.QToolButton(routeEditWidget)
        self.recallPreset_button.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.recallPreset_button.setAutoRaise(True)
        self.recallPreset_button.setObjectName("recallPreset_button")
        self.gridLayout.addWidget(self.recallPreset_button, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(routeEditWidget)
        QtCore.QMetaObject.connectSlotsByName(routeEditWidget)

    def retranslateUi(self, routeEditWidget):
        _translate = QtCore.QCoreApplication.translate
        self.view_button.setToolTip(_translate("routeEditWidget", "View route analysis"))
        self.view_button.setText(_translate("routeEditWidget", "V"))
        self.suggest_button.setToolTip(_translate("routeEditWidget", "Suggest a route"))
        self.suggest_button.setText(_translate("routeEditWidget", "!"))
        self.saveAsPreset_button.setToolTip(_translate("routeEditWidget", "Save current entry as route preset"))
        self.saveAsPreset_button.setText(_translate("routeEditWidget", "S"))
        self.clear_button.setToolTip(_translate("routeEditWidget", "Clear route field"))
        self.clear_button.setText(_translate("routeEditWidget", "X"))
        self.recallPreset_button.setToolTip(_translate("routeEditWidget", "Recall a saved preset"))
        self.recallPreset_button.setText(_translate("routeEditWidget", "R"))
