# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startSoloCtrDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startSoloCtrDialog(object):
    def setupUi(self, startSoloCtrDialog):
        startSoloCtrDialog.setObjectName("startSoloCtrDialog")
        startSoloCtrDialog.resize(382, 147)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(startSoloCtrDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.soloSettings_button = QtWidgets.QPushButton(startSoloCtrDialog)
        self.soloSettings_button.setObjectName("soloSettings_button")
        self.verticalLayout_2.addWidget(self.soloSettings_button)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(startSoloCtrDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.initTrafficCount_edit = QtWidgets.QSpinBox(startSoloCtrDialog)
        self.initTrafficCount_edit.setProperty("value", 5)
        self.initTrafficCount_edit.setObjectName("initTrafficCount_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.initTrafficCount_edit)
        self.simOptions_button = QtWidgets.QPushButton(startSoloCtrDialog)
        self.simOptions_button.setObjectName("simOptions_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.simOptions_button)
        self.label_2 = QtWidgets.QLabel(startSoloCtrDialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(startSoloCtrDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.label.setBuddy(self.initTrafficCount_edit)
        self.label_2.setBuddy(self.simOptions_button)

        self.retranslateUi(startSoloCtrDialog)
        self.buttonBox.rejected.connect(startSoloCtrDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(startSoloCtrDialog)
        startSoloCtrDialog.setTabOrder(self.soloSettings_button, self.simOptions_button)
        startSoloCtrDialog.setTabOrder(self.simOptions_button, self.initTrafficCount_edit)

    def retranslateUi(self, startSoloCtrDialog):
        _translate = QtCore.QCoreApplication.translate
        startSoloCtrDialog.setWindowTitle(_translate("startSoloCtrDialog", "Start a solo centre session"))
        self.soloSettings_button.setText(_translate("startSoloCtrDialog", "Solo system settings..."))
        self.label.setText(_translate("startSoloCtrDialog", "Initial traffic count:"))
        self.simOptions_button.setToolTip(_translate("startSoloCtrDialog", "Can be changed during the session, but initial traffic will be spawned according to these settings."))
        self.simOptions_button.setText(_translate("startSoloCtrDialog", "Solo simulation options..."))
        self.label_2.setText(_translate("startSoloCtrDialog", "Recommended check:"))
