# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startFgSessionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startFgSessionDialog(object):
    def setupUi(self, startFgSessionDialog):
        startFgSessionDialog.setObjectName("startFgSessionDialog")
        startFgSessionDialog.resize(572, 215)
        self.gridLayout = QtWidgets.QGridLayout(startFgSessionDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.voiceSettings_button = QtWidgets.QPushButton(startFgSessionDialog)
        self.voiceSettings_button.setObjectName("voiceSettings_button")
        self.gridLayout.addWidget(self.voiceSettings_button, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(startFgSessionDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.irc_subSystem_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.irc_subSystem_tickBox.setObjectName("irc_subSystem_tickBox")
        self.verticalLayout_2.addWidget(self.irc_subSystem_tickBox)
        self.fgcom_subSystem_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.fgcom_subSystem_tickBox.setObjectName("fgcom_subSystem_tickBox")
        self.verticalLayout_2.addWidget(self.fgcom_subSystem_tickBox)
        self.phone_subSystem_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.phone_subSystem_tickBox.setObjectName("phone_subSystem_tickBox")
        self.verticalLayout_2.addWidget(self.phone_subSystem_tickBox)
        self.orsx_subSystem_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.orsx_subSystem_tickBox.setObjectName("orsx_subSystem_tickBox")
        self.verticalLayout_2.addWidget(self.orsx_subSystem_tickBox)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 3, 1)
        self.groupBox = QtWidgets.QGroupBox(startFgSessionDialog)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.callsign_edit = QtWidgets.QLineEdit(self.groupBox)
        self.callsign_edit.setMaxLength(7)
        self.callsign_edit.setObjectName("callsign_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.callsign_edit)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.clientPort_edit = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientPort_edit.sizePolicy().hasHeightForWidth())
        self.clientPort_edit.setSizePolicy(sizePolicy)
        self.clientPort_edit.setMaximum(65535)
        self.clientPort_edit.setObjectName("clientPort_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.clientPort_edit)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.fgSettings_button = QtWidgets.QPushButton(startFgSessionDialog)
        self.fgSettings_button.setObjectName("fgSettings_button")
        self.gridLayout.addWidget(self.fgSettings_button, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(startFgSessionDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)
        self.label_4.setBuddy(self.callsign_edit)
        self.label_3.setBuddy(self.clientPort_edit)

        self.retranslateUi(startFgSessionDialog)
        self.buttonBox.rejected.connect(startFgSessionDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(startFgSessionDialog)
        startFgSessionDialog.setTabOrder(self.callsign_edit, self.clientPort_edit)
        startFgSessionDialog.setTabOrder(self.clientPort_edit, self.fgSettings_button)
        startFgSessionDialog.setTabOrder(self.fgSettings_button, self.voiceSettings_button)
        startFgSessionDialog.setTabOrder(self.voiceSettings_button, self.irc_subSystem_tickBox)
        startFgSessionDialog.setTabOrder(self.irc_subSystem_tickBox, self.fgcom_subSystem_tickBox)
        startFgSessionDialog.setTabOrder(self.fgcom_subSystem_tickBox, self.phone_subSystem_tickBox)
        startFgSessionDialog.setTabOrder(self.phone_subSystem_tickBox, self.orsx_subSystem_tickBox)

    def retranslateUi(self, startFgSessionDialog):
        _translate = QtCore.QCoreApplication.translate
        startFgSessionDialog.setWindowTitle(_translate("startFgSessionDialog", "Join a FlightGear network"))
        self.voiceSettings_button.setText(_translate("startFgSessionDialog", "Radio/phone settings..."))
        self.groupBox_2.setTitle(_translate("startFgSessionDialog", "Enable sub-systems"))
        self.irc_subSystem_tickBox.setToolTip(_translate("startFgSessionDialog", "Enables CPDLC and coordination with ATC-pie clients (strip exchange, text chat, data link transfers...)"))
        self.irc_subSystem_tickBox.setText(_translate("startFgSessionDialog", "Native ATC-pie messaging"))
        self.fgcom_subSystem_tickBox.setToolTip(_translate("startFgSessionDialog", "Enables integrated radios and ATIS recording (if unticked, third-party software is assumed responsive to PTT, and RDF monitors the publicised frequency)."))
        self.fgcom_subSystem_tickBox.setText(_translate("startFgSessionDialog", "FGCom-mumble radio"))
        self.phone_subSystem_tickBox.setToolTip(_translate("startFgSessionDialog", "Enables direct phone lines with other connected ATC-pie clients (requires ATC-pie messaging)"))
        self.phone_subSystem_tickBox.setText(_translate("startFgSessionDialog", "ATC phone lines"))
        self.orsx_subSystem_tickBox.setToolTip(_translate("startFgSessionDialog", "Enables strip exchange with OpenRadar clients, and provides a (limited) fallback for ATC-pie exchanges when either client has native messaging disabled"))
        self.orsx_subSystem_tickBox.setText(_translate("startFgSessionDialog", "OpenRadar compatibility"))
        self.groupBox.setTitle(_translate("startFgSessionDialog", "Session options"))
        self.label_4.setText(_translate("startFgSessionDialog", "Callsign:"))
        self.callsign_edit.setToolTip(_translate("startFgSessionDialog", "Typically starts with a 4-letter ICAO code, and must be unique on the joined network."))
        self.label_3.setText(_translate("startFgSessionDialog", "Local UDP port:"))
        self.clientPort_edit.setToolTip(_translate("startFgSessionDialog", "Choose a different port for each client if you are connecting more than one from the same host."))
        self.fgSettings_button.setToolTip(_translate("startFgSessionDialog", "Start a FlightGear network session"))
        self.fgSettings_button.setText(_translate("startFgSessionDialog", "FlightGear system settings..."))
