# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startFsdDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startFsdDialog(object):
    def setupUi(self, startFsdDialog):
        startFsdDialog.setObjectName("startFsdDialog")
        startFsdDialog.resize(689, 477)
        self.gridLayout = QtWidgets.QGridLayout(startFsdDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(startFsdDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.callsign_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.callsign_edit.setObjectName("callsign_edit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.callsign_edit)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.visibilityRange_edit = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visibilityRange_edit.sizePolicy().hasHeightForWidth())
        self.visibilityRange_edit.setSizePolicy(sizePolicy)
        self.visibilityRange_edit.setMinimum(10)
        self.visibilityRange_edit.setMaximum(600)
        self.visibilityRange_edit.setSingleStep(10)
        self.visibilityRange_edit.setObjectName("visibilityRange_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.visibilityRange_edit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.voicePort_edit = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voicePort_edit.sizePolicy().hasHeightForWidth())
        self.voicePort_edit.setSizePolicy(sizePolicy)
        self.voicePort_edit.setMaximum(65535)
        self.voicePort_edit.setObjectName("voicePort_edit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.voicePort_edit)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(startFsdDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.line = QtWidgets.QFrame(startFsdDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(startFsdDialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 2)
        self.fsdSettings_button = QtWidgets.QPushButton(startFsdDialog)
        self.fsdSettings_button.setObjectName("fsdSettings_button")
        self.gridLayout.addWidget(self.fsdSettings_button, 1, 0, 1, 1)
        self.subSystems_box = QtWidgets.QGroupBox(startFsdDialog)
        self.subSystems_box.setObjectName("subSystems_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.subSystems_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.use_FGComMumble_tickBox = QtWidgets.QCheckBox(self.subSystems_box)
        self.use_FGComMumble_tickBox.setObjectName("use_FGComMumble_tickBox")
        self.verticalLayout.addWidget(self.use_FGComMumble_tickBox)
        self.use_phoneLines_tickBox = QtWidgets.QCheckBox(self.subSystems_box)
        self.use_phoneLines_tickBox.setObjectName("use_phoneLines_tickBox")
        self.verticalLayout.addWidget(self.use_phoneLines_tickBox)
        self.use_HoppieAcars_tickBox = QtWidgets.QCheckBox(self.subSystems_box)
        self.use_HoppieAcars_tickBox.setObjectName("use_HoppieAcars_tickBox")
        self.verticalLayout.addWidget(self.use_HoppieAcars_tickBox)
        self.gridLayout.addWidget(self.subSystems_box, 0, 1, 3, 1)
        self.voiceSettings_button = QtWidgets.QPushButton(startFsdDialog)
        self.voiceSettings_button.setObjectName("voiceSettings_button")
        self.gridLayout.addWidget(self.voiceSettings_button, 2, 0, 1, 1)
        self.label.setBuddy(self.callsign_edit)
        self.label_4.setBuddy(self.visibilityRange_edit)
        self.label_5.setBuddy(self.voicePort_edit)

        self.retranslateUi(startFsdDialog)
        self.buttonBox.rejected.connect(startFsdDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(startFsdDialog)
        startFsdDialog.setTabOrder(self.callsign_edit, self.visibilityRange_edit)
        startFsdDialog.setTabOrder(self.visibilityRange_edit, self.voicePort_edit)
        startFsdDialog.setTabOrder(self.voicePort_edit, self.fsdSettings_button)
        startFsdDialog.setTabOrder(self.fsdSettings_button, self.voiceSettings_button)
        startFsdDialog.setTabOrder(self.voiceSettings_button, self.use_FGComMumble_tickBox)
        startFsdDialog.setTabOrder(self.use_FGComMumble_tickBox, self.use_phoneLines_tickBox)
        startFsdDialog.setTabOrder(self.use_phoneLines_tickBox, self.use_HoppieAcars_tickBox)

    def retranslateUi(self, startFsdDialog):
        _translate = QtCore.QCoreApplication.translate
        startFsdDialog.setWindowTitle(_translate("startFsdDialog", "Connect to FSD server"))
        self.groupBox_2.setTitle(_translate("startFsdDialog", "Session options"))
        self.label.setText(_translate("startFsdDialog", "Callsign:"))
        self.label_4.setText(_translate("startFsdDialog", "Visibility range:"))
        self.visibilityRange_edit.setToolTip(_translate("startFsdDialog", "Range up to which the server will be informing us of traffic and connections (different from map and radar ranges)"))
        self.visibilityRange_edit.setSuffix(_translate("startFsdDialog", " NM"))
        self.label_5.setText(_translate("startFsdDialog", "Voice UDP port:"))
        self.voicePort_edit.setToolTip(_translate("startFsdDialog", "Choose a different port for each client if you are connecting more than one from the same host."))
        self.label_3.setText(_translate("startFsdDialog", "<html>\n"
"<body>\n"
"<p>Notes on FSD sessions:</p>\n"
"<ul>\n"
"  <li>ask pilots to prefix their &quot;real name&quot; setting with the ICAO type designator of their aircraft and a double slash, e.g. &quot;C172//Joanna Doe&quot;—this will allow to render the correct model in the FG views, and to display the correct XPDR info when you cheat it;</li>\n"
"  <li>text radio is tuned to the frequency publicised from the radio panel;</li>\n"
"  <li>if you enable Hoppie ACARS, make sure you have set your <a href=\"https://www.hoppie.nl/acars/system/account.html\">account</a> to log on the \"None\" network, and that you start with an unused callsign (see <a href=\"https://www.hoppie.nl/acars/system/online.html\">currently logged stations</a>).</li>\n"
"</ul>\n"
"<p>Protocol limitations:</p>\n"
"<ul>\n"
"  <li>transponders are not capable of mode S, and squawked altitudes/FLs are not pressure-altitudes;</li>\n"
"  <li>flight plans can only be filed or amended by the pilots.</li>\n"
"</ul>\n"
"</body>\n"
"</html>"))
        self.fsdSettings_button.setToolTip(_translate("startFsdDialog", "Start an FSD network session"))
        self.fsdSettings_button.setText(_translate("startFsdDialog", "FSD system settings..."))
        self.subSystems_box.setTitle(_translate("startFsdDialog", "Enable sub-systems"))
        self.use_FGComMumble_tickBox.setToolTip(_translate("startFsdDialog", "Enables integrated radios, RDF, ATIS recording (if unticked, third-party software is assumed responsive to PTT)."))
        self.use_FGComMumble_tickBox.setText(_translate("startFsdDialog", "FGCom-mumble radio"))
        self.use_phoneLines_tickBox.setText(_translate("startFsdDialog", "ATC phone lines"))
        self.use_HoppieAcars_tickBox.setToolTip(_translate("startFsdDialog", "Enables CPDLC"))
        self.use_HoppieAcars_tickBox.setText(_translate("startFsdDialog", "Hoppie\'s ACARS service"))
        self.voiceSettings_button.setText(_translate("startFsdDialog", "Radio/phone settings..."))
