# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'startPlaybackSessionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_startPlaybackDialog(object):
    def setupUi(self, startPlaybackDialog):
        startPlaybackDialog.setObjectName("startPlaybackDialog")
        startPlaybackDialog.resize(392, 162)
        self.verticalLayout = QtWidgets.QVBoxLayout(startPlaybackDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(startPlaybackDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dataFile_info = QtWidgets.QLabel(startPlaybackDialog)
        self.dataFile_info.setObjectName("dataFile_info")
        self.horizontalLayout.addWidget(self.dataFile_info)
        self.browse_button = QtWidgets.QToolButton(startPlaybackDialog)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.timeline_info = QtWidgets.QLabel(startPlaybackDialog)
        self.timeline_info.setObjectName("timeline_info")
        self.verticalLayout.addWidget(self.timeline_info)
        self.buttonBox = QtWidgets.QDialogButtonBox(startPlaybackDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(startPlaybackDialog)
        self.buttonBox.rejected.connect(startPlaybackDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(startPlaybackDialog)

    def retranslateUi(self, startPlaybackDialog):
        _translate = QtCore.QCoreApplication.translate
        startPlaybackDialog.setWindowTitle(_translate("startPlaybackDialog", "Play back recorded data"))
        self.label.setText(_translate("startPlaybackDialog", "Data file:"))
        self.dataFile_info.setText(_translate("startPlaybackDialog", "###"))
        self.browse_button.setToolTip(_translate("startPlaybackDialog", "Browse"))
        self.browse_button.setText(_translate("startPlaybackDialog", "Browse..."))
        self.timeline_info.setText(_translate("startPlaybackDialog", "###"))
