# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stripRackPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_stripRackPanel(object):
    def setupUi(self, stripRackPanel):
        stripRackPanel.setObjectName("stripRackPanel")
        stripRackPanel.resize(580, 255)
        self.verticalLayout = QtWidgets.QVBoxLayout(stripRackPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stacked_view_widget = QtWidgets.QStackedWidget(stripRackPanel)
        self.stacked_view_widget.setObjectName("stacked_view_widget")
        self.tableView_page = QtWidgets.QWidget()
        self.tableView_page.setObjectName("tableView_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tableView_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stripRacks_view = StripTableView(self.tableView_page)
        self.stripRacks_view.setObjectName("stripRacks_view")
        self.verticalLayout_3.addWidget(self.stripRacks_view)
        self.stacked_view_widget.addWidget(self.tableView_page)
        self.tabView_page = QtWidgets.QWidget()
        self.tabView_page.setObjectName("tabView_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabView_page)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stripRacks_tabs = StripRackTabs(self.tabView_page)
        self.stripRacks_tabs.setMouseTracking(False)
        self.stripRacks_tabs.setTabPosition(QtWidgets.QTabWidget.South)
        self.stripRacks_tabs.setMovable(True)
        self.stripRacks_tabs.setObjectName("stripRacks_tabs")
        self.verticalLayout_2.addWidget(self.stripRacks_tabs)
        self.stacked_view_widget.addWidget(self.tabView_page)
        self.verticalLayout.addWidget(self.stacked_view_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view_menuButton = QtWidgets.QToolButton(stripRackPanel)
        self.view_menuButton.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.view_menuButton.setObjectName("view_menuButton")
        self.horizontalLayout_2.addWidget(self.view_menuButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.strip_menuButton = StripMenuButton(stripRackPanel)
        self.strip_menuButton.setObjectName("strip_menuButton")
        self.horizontalLayout_2.addWidget(self.strip_menuButton)
        self.frame = QtWidgets.QFrame(stripRackPanel)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shelf_button = ShelfButtonWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shelf_button.sizePolicy().hasHeightForWidth())
        self.shelf_button.setSizePolicy(sizePolicy)
        self.shelf_button.setMinimumSize(QtCore.QSize(50, 0))
        self.shelf_button.setObjectName("shelf_button")
        self.horizontalLayout.addWidget(self.shelf_button)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(stripRackPanel)
        self.stacked_view_widget.setCurrentIndex(0)
        self.stripRacks_tabs.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(stripRackPanel)
        stripRackPanel.setTabOrder(self.stripRacks_view, self.stripRacks_tabs)
        stripRackPanel.setTabOrder(self.stripRacks_tabs, self.view_menuButton)
        stripRackPanel.setTabOrder(self.view_menuButton, self.strip_menuButton)

    def retranslateUi(self, stripRackPanel):
        _translate = QtCore.QCoreApplication.translate
        stripRackPanel.setWindowTitle(_translate("stripRackPanel", "Strip racks"))
        self.view_menuButton.setText(_translate("stripRackPanel", "Opts"))
        self.strip_menuButton.setText(_translate("stripRackPanel", "..."))
from gui.widgets.stripView import ShelfButtonWidget, StripMenuButton, StripRackTabs, StripTableView
