# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textRadioPanel.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_textRadioPanel(object):
    def setupUi(self, textRadioPanel):
        textRadioPanel.setObjectName("textRadioPanel")
        textRadioPanel.resize(678, 192)
        self.verticalLayout = QtWidgets.QVBoxLayout(textRadioPanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.msgHistory_view = QtWidgets.QTableView(textRadioPanel)
        self.msgHistory_view.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.msgHistory_view.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.msgHistory_view.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.msgHistory_view.setShowGrid(False)
        self.msgHistory_view.setObjectName("msgHistory_view")
        self.msgHistory_view.horizontalHeader().setVisible(False)
        self.msgHistory_view.horizontalHeader().setStretchLastSection(True)
        self.msgHistory_view.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.msgHistory_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toFrom_label = QtWidgets.QLabel(textRadioPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toFrom_label.sizePolicy().hasHeightForWidth())
        self.toFrom_label.setSizePolicy(sizePolicy)
        self.toFrom_label.setObjectName("toFrom_label")
        self.horizontalLayout.addWidget(self.toFrom_label)
        self.dest_combo = QtWidgets.QComboBox(textRadioPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dest_combo.sizePolicy().hasHeightForWidth())
        self.dest_combo.setSizePolicy(sizePolicy)
        self.dest_combo.setEditable(True)
        self.dest_combo.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.dest_combo.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.dest_combo.setMinimumContentsLength(10)
        self.dest_combo.setObjectName("dest_combo")
        self.horizontalLayout.addWidget(self.dest_combo)
        self.label_2 = QtWidgets.QLabel(textRadioPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.msgLine_combo = QtWidgets.QComboBox(textRadioPanel)
        self.msgLine_combo.setEditable(True)
        self.msgLine_combo.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.msgLine_combo.setObjectName("msgLine_combo")
        self.horizontalLayout.addWidget(self.msgLine_combo)
        self.send_button = QtWidgets.QToolButton(textRadioPanel)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout.addWidget(self.send_button)
        self.menu_button = QtWidgets.QToolButton(textRadioPanel)
        self.menu_button.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout.addWidget(self.menu_button)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(textRadioPanel)
        QtCore.QMetaObject.connectSlotsByName(textRadioPanel)
        textRadioPanel.setTabOrder(self.msgHistory_view, self.dest_combo)
        textRadioPanel.setTabOrder(self.dest_combo, self.msgLine_combo)
        textRadioPanel.setTabOrder(self.msgLine_combo, self.send_button)

    def retranslateUi(self, textRadioPanel):
        _translate = QtCore.QCoreApplication.translate
        self.toFrom_label.setText(_translate("textRadioPanel", "To:"))
        self.label_2.setText(_translate("textRadioPanel", "Msg:"))
        self.send_button.setText(_translate("textRadioPanel", "Send"))
        self.menu_button.setText(_translate("textRadioPanel", "Opts"))
