# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewpointsSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_viewpointsSettingsDialog(object):
    def setupUi(self, viewpointsSettingsDialog):
        viewpointsSettingsDialog.setObjectName("viewpointsSettingsDialog")
        viewpointsSettingsDialog.resize(611, 247)
        self.verticalLayout = QtWidgets.QVBoxLayout(viewpointsSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(viewpointsSettingsDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.table_view = QtWidgets.QTableView(viewpointsSettingsDialog)
        self.table_view.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table_view.setShowGrid(False)
        self.table_view.setObjectName("table_view")
        self.verticalLayout.addWidget(self.table_view)
        self.info_label = QtWidgets.QLabel(viewpointsSettingsDialog)
        font = QtGui.QFont()
        font.setItalic(True)
        self.info_label.setFont(font)
        self.info_label.setObjectName("info_label")
        self.verticalLayout.addWidget(self.info_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.createViewpoint_button = QtWidgets.QToolButton(viewpointsSettingsDialog)
        self.createViewpoint_button.setObjectName("createViewpoint_button")
        self.horizontalLayout.addWidget(self.createViewpoint_button)
        self.removeViewpoint_button = QtWidgets.QToolButton(viewpointsSettingsDialog)
        self.removeViewpoint_button.setObjectName("removeViewpoint_button")
        self.horizontalLayout.addWidget(self.removeViewpoint_button)
        self.buttonBox = QtWidgets.QDialogButtonBox(viewpointsSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label.setBuddy(self.table_view)

        self.retranslateUi(viewpointsSettingsDialog)
        self.buttonBox.rejected.connect(viewpointsSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(viewpointsSettingsDialog)

    def retranslateUi(self, viewpointsSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        viewpointsSettingsDialog.setWindowTitle(_translate("viewpointsSettingsDialog", "Location viewpoints"))
        self.label.setText(_translate("viewpointsSettingsDialog", "Select active tower viewpoint:"))
        self.info_label.setText(_translate("viewpointsSettingsDialog", "If no viewpoint is available, tower view will be positioned somewhere on the airfield."))
        self.createViewpoint_button.setToolTip(_translate("viewpointsSettingsDialog", "Create new viewpoint"))
        self.createViewpoint_button.setText(_translate("viewpointsSettingsDialog", "+"))
        self.removeViewpoint_button.setToolTip(_translate("viewpointsSettingsDialog", "Delete selected viewpoint"))
        self.removeViewpoint_button.setText(_translate("viewpointsSettingsDialog", "–"))
