# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'voiceSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_voiceSettingsDialog(object):
    def setupUi(self, voiceSettingsDialog):
        voiceSettingsDialog.setObjectName("voiceSettingsDialog")
        voiceSettingsDialog.resize(431, 327)
        self.verticalLayout = QtWidgets.QVBoxLayout(voiceSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(voiceSettingsDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_52)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.fgcomMumbleHost_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.fgcomMumbleHost_edit.setObjectName("fgcomMumbleHost_edit")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgcomMumbleHost_edit)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.fgcomMumblePort_edit = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgcomMumblePort_edit.sizePolicy().hasHeightForWidth())
        self.fgcomMumblePort_edit.setSizePolicy(sizePolicy)
        self.fgcomMumblePort_edit.setMaximum(65535)
        self.fgcomMumblePort_edit.setObjectName("fgcomMumblePort_edit")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgcomMumblePort_edit)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fgcomMumbleSoundEffects_tickBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.fgcomMumbleSoundEffects_tickBox.setObjectName("fgcomMumbleSoundEffects_tickBox")
        self.horizontalLayout_8.addWidget(self.fgcomMumbleSoundEffects_tickBox)
        self.testFGComMumble_button = QtWidgets.QToolButton(self.groupBox_2)
        self.testFGComMumble_button.setObjectName("testFGComMumble_button")
        self.horizontalLayout_8.addWidget(self.testFGComMumble_button)
        self.formLayout_5.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout_8)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.pyaudioPhone_groupBox = QtWidgets.QGroupBox(voiceSettingsDialog)
        self.pyaudioPhone_groupBox.setObjectName("pyaudioPhone_groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.pyaudioPhone_groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.pyaudioPhone_groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.phoneIP_edit = QtWidgets.QLineEdit(self.pyaudioPhone_groupBox)
        self.phoneIP_edit.setObjectName("phoneIP_edit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.phoneIP_edit)
        self.label_2 = QtWidgets.QLabel(self.pyaudioPhone_groupBox)
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.verticalLayout.addWidget(self.pyaudioPhone_groupBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(voiceSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_41.setBuddy(self.fgcomMumbleHost_edit)
        self.label_13.setBuddy(self.fgcomMumblePort_edit)
        self.label.setBuddy(self.phoneIP_edit)

        self.retranslateUi(voiceSettingsDialog)
        self.buttonBox.rejected.connect(voiceSettingsDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(voiceSettingsDialog)
        voiceSettingsDialog.setTabOrder(self.fgcomMumbleHost_edit, self.fgcomMumblePort_edit)
        voiceSettingsDialog.setTabOrder(self.fgcomMumblePort_edit, self.fgcomMumbleSoundEffects_tickBox)
        voiceSettingsDialog.setTabOrder(self.fgcomMumbleSoundEffects_tickBox, self.testFGComMumble_button)
        voiceSettingsDialog.setTabOrder(self.testFGComMumble_button, self.phoneIP_edit)

    def retranslateUi(self, voiceSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        voiceSettingsDialog.setWindowTitle(_translate("voiceSettingsDialog", "FG/FSD radio and phone settings"))
        self.groupBox_2.setTitle(_translate("voiceSettingsDialog", "FGCom-mumble radio"))
        self.label_52.setText(_translate("voiceSettingsDialog", "Requires a Mumble client running the FGCom plug-in"))
        self.label_41.setText(_translate("voiceSettingsDialog", "Running host:"))
        self.label_13.setText(_translate("voiceSettingsDialog", "Control port:"))
        self.fgcomMumbleSoundEffects_tickBox.setText(_translate("voiceSettingsDialog", "Realistic sound effects (e.g. static)"))
        self.testFGComMumble_button.setToolTip(_translate("voiceSettingsDialog", "Run an echo test for this FGCom-mumble configuration"))
        self.testFGComMumble_button.setText(_translate("voiceSettingsDialog", "Test..."))
        self.pyaudioPhone_groupBox.setTitle(_translate("voiceSettingsDialog", "ATC phone lines"))
        self.label.setText(_translate("voiceSettingsDialog", "Reachable IP for this instance:"))
        self.label_2.setText(_translate("voiceSettingsDialog", "Requires PyAudio"))
